### ISSUE TITLE
Any plans to add text / scrolling functions

### ISSUE THREAD

**Issue by dsssssssss9** [matthiasamberg/pxt-ledmatrix#1]
Hello

Just discovered your greate Extension - works a lot better than all the others I have tried - much easier to understand due to the good documentation as well!!

Could i trouble You by asking if you might ever add text display / scrolling functions?

I am trying to make a project that needs to do this - all the other extensions i have tried either require a Zig Zag matrix, or don't work well with smaller displays ( 8x8 etc)

**Comment by matthiasamberg** [comment]
Hi [dsssssssss9](https://github.com/dsssssssss9) 

this is not a planned enhancement at the moment. But I would merge such additional features into the library if provided. 
Beste Matthias

**Comment by dsssssssss9** [comment]
My sincere thanks for getting back to me...
